apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "deploy-datapipeline"
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 40
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  accessPolicy:
    outbound:
      external:
        - host: vera.nais.oera.no
        - host: bigquery.googleapis.com
        - host: dv-api-intern.prod-gcp.nais.io
        - host: dv-api-ekstern.prod-gcp.nais.io
        - host: datakatalogen.intern.nav.no
  gcp:
    buckets:
      - name: deployments-vera
