name: Apply

on:
  push:
    branches:
      - "main"
    paths:
      - "bigquery/terraform**"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.13.0

      - name: Terraform setup credentials
        id: credentials
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
        run: echo $GCP_KEY > ${GITHUB_WORKSPACE}/sa.json

      - name: Set GOOGLE_CREDENTIALS
        id: google-cred
        run: echo "GOOGLE_CREDENTIALS=$(echo ${GITHUB_WORKSPACE}/sa.json)" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: bigquery/terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color plan.zip
        working-directory: bigquery/terraform
        continue-on-error: true

      - name: Add comment
        uses: actions/github-script@v3.1.0
        env:
          APPLY: "terraform apply\n${{ steps.apply.outputs.stdout }}\n${{ steps.apply.outputs.stderr }}"
        with:
          script: |
            const apply = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/apply.js`)(github, context, core)
            await apply.addComment({
                init: "${{ steps.init.outcome }}",
                apply: "${{ steps.apply.outcome }}",
            })

      - name: Expose job result
        id: result
        uses: actions/github-script@v3.1.0
        with:
          result-encoding: string
          script: |
            const lib = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/lib.js`)(github, context)
            return lib.exposeJobResult(${{toJSON(steps)}})

    outputs:
      result: "${{ steps.result.outputs.result }}"

  labelOk:
    runs-on: ubuntu-latest
    needs:
      - apply
    if: needs.apply.outputs.result == 'success'
    steps:
      - name: Add terraform/apply:OK label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: terraform/apply:OK

      - name: Remove terraform/apply:FAIL label
        uses: actions-ecosystem/action-remove-labels@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: terraform/apply:FAIL

  labelFail:
    runs-on: ubuntu-latest
    needs:
      - apply
    if: needs.apply.outputs.result != 'success'
    steps:
      - name: Add terraform/apply:FAIL label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: terraform/apply:FAIL

      - name: Remove terraform/apply:OK label
        uses: actions-ecosystem/action-remove-labels@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: terraform/apply:OK

      - name: Fail the workflow
        run: |
          echo "::error ::The result of apply was '${{ needs.apply.outputs.result }}'"
          exit 1